grpc:
  client:
    user-service:
      address: static://localhost:6565
      negotiationType: plaintext
    movie-service:
      address: static://localhost:7575
      negotiationType: TLS
      security:
        trustCertCollection: file:C:/Users/zikoz/Desktop/gPRC/ssl_tls/ca.cert.pem


#Using ssl for movie-service

